---
title: "02_5_DESeq_Foot_TC_genome"
output: html_document
date: "2024-06-15"
---

```{r paths, include=FALSE}
source(here::here("01_code", "_paths.R"))
```

```{r load libraries}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install(version = "3.16")

BiocManager::install("DESeq2")
library("DESeq2") # Bioconductor
library("tidyverse")
library("dplyr")
library("pheatmap")
library("RColorBrewer")
library("genefilter") # Bioconductor
library("ggplot2")
library("gplots")
library("limma") # Bioconductor
install.packages("spdep")
library("spdep") 
library("adegenet")
library("tximport") # Bioconductor
BiocManager::install("vsn")
BiocManager::install("tidybulk")
BiocManager::install("goseq")
BiocManager::install("affycoretools")
BiocManager::install("EnhancedVolcano")
BiocManager::install("pcaExplorer")
BiocManager::install("apeglm")
BiocManager::install("PCAtools")
BiocManager::install("DESeq2PCA")
library(pcaExplorer)
library(PCAtools)
```

### Load and clean up treatment info and gene count matrix 
```{r}
# Read in treatment info file
treatmentinfo <- read_csv(file.path(dat, "treatmentinfo_clean.csv"))

# read in count matrix
gene_count_matrix_clean_og <- read_delim(file.path(dat, "gene_count_matrix_clean.csv"), delim = ",")

# make transcripts the row names
rownames <- gene_count_matrix_clean$...1

# clean up count matrix matrix, make transcripts the rownames
gene_count_matrix_clean <- subset(gene_count_matrix_clean, select = -c(...1))
rownames(gene_count_matrix_clean) <- rownames

# make count matrix into a matrix
gene_count_matrix_clean <- data.matrix(gene_count_matrix_clean)
```

### All foot tissue, TC (treatment control)
```{r}
# read in files
treatmentinfo3 <- read_delim(file.path(dat, "treatmentinfo_clean.csv"), delim = ",")
gene_count_matrix_clean <- read_delim(file.path(dat, "gene_count_matrix_clean.csv"), delim = ",")

# filter out gill tissue and lab control
F_TC_treatmentinfo  <- treatmentinfo3  %>% filter(tissue == "F") %>%
  filter(!( tissue == "G"))
F_TC_treatmentinfo  <- F_TC_treatmentinfo  %>% 
  filter(!(  treatment== "control" & day == 0))

# write the filtered treatment info file
write.table(F_TC_treatmentinfo, file = file.path(deg, "Foot/F_TC_treatmentinfo.csv"), row.names = FALSE)

# subset count matrix and save
F_TC_countmatrix <- subset(gene_count_matrix_clean, select=(F_TC_treatmentinfo$sample.1))
F_TC_countmatrix <- data.frame(F_TC_countmatrix)
write.table(F_TC_countmatrix, file = file.path(deg, "Foot/F_TC_countmatrix.csv"))

# CaTCulate DESeq object
dds25 <- DESeqDataSetFromMatrix(countData = F_TC_countmatrix,
                              colData = F_TC_treatmentinfo,
                              design = ~ treatment)

dds25 <- DESeq(dds25)
resultsNames(dds25) # lists the coefficients

# graph dds results
PCAdata <- plotPCA(vst(dds25), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level = 0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Treatment control", "Hypoxia", "Ocean acidification", "Ocean warming"), values = c("purple", "green", "red", "orange"))+
  guides(color=guide_legend("Treatment"))+
  theme(axis.text = element_text(size =18, color = "black"))+
  theme(axis.title = element_text(size =20, color = "black"))+
  theme(legend.text = element_text(size =18, color = "black"))+
  theme(legend.title = element_text(size =20, color = "black"))+
  theme(aspect.ratio = 1)


```

### All tissue all treatments
```{r}
# read in files
treatmentinfo <- read_csv(file.path(dat, "treatmentinfo_clean.csv"))
gene_count_matrix_clean <- read_delim(file.path(dat, "gene_count_matrix_clean.csv"), delim = ",")

# filter out lab control
TC_treatmentinfo <- treatmentinfo %>%
  filter(!(day == "0")) 

#subset and save count matrix
TC_countmatrix <- subset(gene_count_matrix_clean, select=(TC_treatmentinfo$sample.1))
TC_countmatrix <- data.frame(TC_countmatrix)
write.table(TC_countmatrix, file = file.path(deg, "TC_countmatrix.csv"))

# CaTCulate DESeq object
dds26 <- DESeqDataSetFromMatrix(countData = TC_countmatrix,
                              colData = TC_treatmentinfo,
                              design = ~ treatment + tissue + tissue:treatment)

dds26 <- DESeq(dds26)
resultsNames(dds26) # lists the coefficients

# graph dds results
PCAdata <- plotPCA(vst(dds26), intgroup = c("tissue", "treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment, shape = tissue)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level = 0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Treatment control", "Hypoxia", "Ocean acidification", "Ocean warming"), values = c("purple", "green", "red", "orange"))+
  scale_shape_manual(labels = c("Foot", "Gill"), values = c("circle", "triangle"))+
  guides(color=guide_legend("Treatment"), shape = guide_legend("Tissue"))+
  theme(axis.text = element_text(size =18, color = "black"))+
  theme(axis.title = element_text(size =20, color = "black"))+
  theme(legend.text = element_text(size =18, color = "black"))+
  theme(legend.title = element_text(size =20, color = "black"))+
  theme(aspect.ratio = 1)

```



### OA vs treatment control
```{r}
# DEG in the foot after exposure to ocean acidification plus treatment control samples
FOA_TC_treatmentinfo <- read_delim(file.path(deg, "Foot/FOA_TC_treatmentinfo.csv"), delim = " ")

# subset foot OA samples from count matrix
FOA_TC_countmatrix <- subset(gene_count_matrix_clean, select=(FOA_TC_treatmentinfo$sample.1))
FOA_TC_countmatrix <- data.frame(FOA_TC_countmatrix)
write.table(FOA_TC_countmatrix, file = file.path(deg, "Foot/FOA_TC_countmatrix.csv"))

# CaTCulate DESeq object
dds9 <- DESeqDataSetFromMatrix(countData = FOA_TC_countmatrix,
                              colData = FOA_TC_treatmentinfo,
                              design = ~ treatment)

dds9 <- DESeq(dds9)
resultsNames(dds9) # lists the coefficients

# graph dds results
PCAdata <- plotPCA(vst(dds9), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level = 0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Treatment control", "Ocean acidification"), values = c("purple", "red"))+
  guides(color=guide_legend("Treatment"))+
  theme(axis.text = element_text(size =18, color = "black"))+
  theme(axis.title = element_text(size =20, color = "black"))+
  theme(legend.text = element_text(size =18, color = "black"))+
  theme(legend.title = element_text(size =20, color = "black"))


# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds9) >= 10) >= ncol(FOA_TC_countmatrix)/3
dds9_filt <- dds9[keep,]

```

### OW vs treatment control
```{r}
# read in specific treatment info file
FOW_TC_treatmentinfo <- read_delim(file.path(deg, "Foot/FOW_TC_treatmentinfo.csv"), delim = " ")
                  
# Subset foot ocean warming samples from count matrix                                                                               
FOW_TC_countmatrix <- subset(gene_count_matrix_clean, select=(FOW_TC_treatmentinfo$sample.1))
write.table(FOW_TC_countmatrix, file = file.path(deg, "Foot/FOW_TC_countmatrix.csv"))

# CaTCulate DESeq object
dds10 <- DESeqDataSetFromMatrix(countData = FOW_TC_countmatrix,
                              colData = FOW_TC_treatmentinfo,
                              design = ~ treatment)

dds10 <- DESeq(dds10)
resultsNames(dds10) # lists the coefficients

# graph dds results
PCAdata <- plotPCA(vst(dds10), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Treatment control", "Ocean warming"), values = c("purple", "orange"))+
  guides(color=guide_legend("Treatment"))+
  theme(axis.text = element_text(size =18, color = "black"))+
  theme(axis.title = element_text(size =20, color = "black"))+
  theme(legend.text = element_text(size =18, color = "black"))+
  theme(legend.title = element_text(size =20, color = "black"))



# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds10) >= 10) >= ncol(FOW_TC_countmatrix)/3
dds10_filt <- dds10[keep,]

```

### DO vs treatment control
```{r}
# read in specific treatment info file
FDO_TC_treatmentinfo <- read_delim(file.path(deg, "Foot/FDO_TC_treatmentinfo.csv"), delim = " ")

# subset foot hypoxoia samples from count matrix                                                                                     
FDO_TC_countmatrix <- subset(gene_count_matrix_clean, select=(FDO_TC_treatmentinfo$sample.1))
write.table(FDO_TC_countmatrix, file = file.path(deg, "Foot/FDO_TC_countmatrix.csv"))

# CaTCulate DESeq object
dds11 <- DESeqDataSetFromMatrix(countData = FDO_TC_countmatrix,
                              colData = FDO_TC_treatmentinfo,
                              design = ~ treatment)

dds11 <- DESeq(dds11)
resultsNames(dds11) # lists the coefficients

# graph dds results
PCAdata <- plotPCA(vst(dds11), intgroup = c("treatment"), returnData=TRUE)
percentVar <- round(100*attr(PCAdata, "percentVar")) #plot PCA of samples with all data
ggplot(PCAdata, aes(PC1, PC2, color=treatment)) + 
  geom_point(size=4, alpha = 5/10) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed()+
  stat_ellipse(level=0.95)+
  theme_classic()+
  scale_color_manual(labels = c("Treatment control", "Hypoxia"), values = c("purple", "green"))+
  guides(color=guide_legend("Treatment"))+
  theme(axis.text = element_text(size =18, color = "black"))+
  theme(axis.title = element_text(size =20, color = "black"))+
  theme(legend.text = element_text(size =18, color = "black"))+
  theme(legend.title = element_text(size =20, color = "black"))


# Filtering: keep genes that have at least 10 counts across 1/3 of the samples - https://support.bioconductor.org/p/110307/
keep <- rowSums(DESeq2::counts(dds11) >= 10) >= ncol(FDO_TC_countmatrix)/3
dds11_filt <- dds11[keep,]

```


