---
title: "DEG_list_cleanup"
output: html_document
date: "2025-10-30"
---

```{r paths, include=FALSE}
source(here::here("01_code", "_paths.R"))
```

```{r}
install.packages("tidyverse")
library(tidyverse)
```

```{r}
FDO_sigs <- read_csv(file.path(deg, "GOterms_genome/FDO_sigs_merged.csv"))
FOA_sigs <- read_csv(file.path(deg, "GOterms_genome/FOA_sigs_merged.csv"))
FOW_sigs <- read_csv(file.path(deg, "GOterms_genome/FOW_sigs_merged.csv"))

GDO_sigs <- read_csv(file.path(deg, "GOterms_genome/GDO_sigs_merged.csv"))
GOA_sigs <- read_csv(file.path(deg, "GOterms_genome/GOA_sigs_merged.csv"))
GOW_sigs <- read_csv(file.path(deg, "GOterms_genome/GOW_sigs_merged.csv"))

```
```{r}
FDO_sigs_clean <- FDO_sigs %>%
  subset(select = c(gene, baseMean, log2FoldChange, lfcSE, padj, protein_name))

FOW_sigs_clean <- FOW_sigs %>%
  subset(select = c(gene, baseMean, log2FoldChange, lfcSE, padj, protein_name))

FOA_sigs_clean <- FOA_sigs %>%
  subset(select = c(gene, baseMean, log2FoldChange, lfcSE, padj, protein_name))

GDO_sigs_clean <- GDO_sigs %>%
  subset(select = c(gene, baseMean, log2FoldChange, lfcSE, padj, protein_name))

GOA_sigs_clean <- GOA_sigs %>%
  subset(select = c(gene, baseMean, log2FoldChange, lfcSE, padj, protein_name))

GOW_sigs_clean <- GOW_sigs %>%
  subset(select = c(gene, baseMean, log2FoldChange, lfcSE, padj, protein_name))

write_csv(FDO_sigs_clean, file.path(deg, "GOterms_genome/clean_zenodo_files/FDO_sigs_zenodo"))

write_csv(FOW_sigs_clean, file.path(deg, "GOterms_genome/clean_zenodo_files/FOW_sigs_zenodo"))

write_csv(FOA_sigs_clean, file.path(deg, "GOterms_genome/clean_zenodo_files/FOA_sigs_zenodo"))

write_csv(GDO_sigs_clean, file.path(deg, "GOterms_genome/clean_zenodo_files/GDO_sigs_zenodo"))

write_csv(GOW_sigs_clean, file.path(deg, "GOterms_genome/clean_zenodo_files/GOW_sigs_zenodo"))

write_csv(GOA_sigs_clean, file.path(deg, "GOterms_genome/clean_zenodo_files/GOA_sigs_zenodo"))

```

